package paneles;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Cursor;
import phms.Connect;
import phms.OTP;

public class UserHome extends javax.swing.JPanel {

    static String unm="",dbname=null,otp_ack=null;
    public String email=null,oldmail=null,otp_mail=null;
    public Statement st;
    public Connect c=new Connect();
    public int otp;
    Random rand=new Random();
    public JLabel[] labels=new JLabel[8];
    public int ct=0;
    
    public UserHome(String unm,String otp_ack,String otp_mail) {

        this.unm=unm;   this.otp_ack=otp_ack; this.otp_mail=otp_mail;
        dbname=unm.toLowerCase().replaceAll(" ","");        
        st=c.connection("userdatabase");       
        initComponents();
        labels[0]=table1;labels[1]=table2;labels[2]=table3;labels[3]=table4;labels[4]=table5;labels[5]=table6;labels[6]=table7;labels[7]=table8;

        for(int i=0;i<8;i++)
            labels[i].setVisible(false);
            
        uname.setText(unm);
        try
        {
            ResultSet rs=st.executeQuery("select * from users where name='"+unm+"'");
            while(rs.next())
            {      
                umail.setText(rs.getString("Email"));
                upass.setText(rs.getString("Password"));
                oldmail=rs.getString("Email");
            }

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbname+"?useTimezone=true&serverTimezone=IST","root","");                      
            DatabaseMetaData meta=(DatabaseMetaData) con.getMetaData();
            rs=meta.getTables(null,null,"%", new String []{"TABLE"});            
            while(rs.next())
            {
                if(rs.getString(1).equals(dbname))
                {
                    String str=rs.getString("TABLE_NAME");
                    labels[ct].setText(str);
                    labels[ct++].setVisible(true);
                }
            }            
        }
        catch(Exception e){ System.out.println("Exception aayi h "+e.getMessage());}
        
        if(otp_ack.equals("true"))
        {
            int i=0;
            try
            {
                i=st.executeUpdate("update users set Email='"+otp_mail+"' where name='"+unm+"'");
            }   
            catch(Exception e2){System.out.println("Exception aayi h OTP wale me"+e2.getMessage());}                           
            if(i>0)
                JOptionPane.showMessageDialog(null,"Email updated successfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
            else
                System.out.println("Nai hua Update");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Lpname = new javax.swing.JLabel();
        Lpname2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Lpname5 = new javax.swing.JLabel();
        table1 = new javax.swing.JLabel();
        table2 = new javax.swing.JLabel();
        table3 = new javax.swing.JLabel();
        table4 = new javax.swing.JLabel();
        table5 = new javax.swing.JLabel();
        table6 = new javax.swing.JLabel();
        table7 = new javax.swing.JLabel();
        table8 = new javax.swing.JLabel();
        umail = new javax.swing.JTextField();
        upass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 239, 186));
        setMinimumSize(new java.awt.Dimension(822, 658));
        setPreferredSize(new java.awt.Dimension(822, 658));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 81, 94));
        jLabel2.setText("Welcome");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 43, -1, -1));

        uname.setFont(new java.awt.Font("Bahnschrift", 0, 34)); // NOI18N
        uname.setForeground(new java.awt.Color(64, 81, 94));
        uname.setText("uname");
        add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 123, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homeai.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 154, -1, 307));

        Lpname.setBackground(new java.awt.Color(249, 248, 235));
        Lpname.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        Lpname.setForeground(new java.awt.Color(64, 81, 94));
        Lpname.setText("Monitoring Plants:");
        add(Lpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 486, -1, -1));

        Lpname2.setBackground(new java.awt.Color(249, 248, 235));
        Lpname2.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        Lpname2.setForeground(new java.awt.Color(64, 81, 94));
        Lpname2.setText("Email Id:");
        add(Lpname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 227, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(233, 239, 186));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 299, 256, 10));

        jSeparator2.setBackground(new java.awt.Color(233, 239, 186));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 423, 256, 10));

        Lpname5.setBackground(new java.awt.Color(249, 248, 235));
        Lpname5.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        Lpname5.setForeground(new java.awt.Color(64, 81, 94));
        Lpname5.setText("Password:");
        add(Lpname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 351, -1, -1));

        table1.setBackground(new java.awt.Color(249, 248, 235));
        table1.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        table1.setForeground(new java.awt.Color(64, 81, 94));
        table1.setText("table1");
        add(table1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 552, -1, -1));

        table2.setBackground(new java.awt.Color(249, 248, 235));
        table2.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        table2.setForeground(new java.awt.Color(64, 81, 94));
        table2.setText("table2");
        add(table2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 592, -1, -1));

        table3.setBackground(new java.awt.Color(249, 248, 235));
        table3.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        table3.setForeground(new java.awt.Color(64, 81, 94));
        table3.setText("table3");
        add(table3, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 552, -1, -1));

        table4.setBackground(new java.awt.Color(249, 248, 235));
        table4.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        table4.setForeground(new java.awt.Color(64, 81, 94));
        table4.setText("table4");
        add(table4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 592, -1, -1));

        table5.setBackground(new java.awt.Color(249, 248, 235));
        table5.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        table5.setForeground(new java.awt.Color(64, 81, 94));
        table5.setText("table5");
        add(table5, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 552, -1, -1));

        table6.setBackground(new java.awt.Color(249, 248, 235));
        table6.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        table6.setForeground(new java.awt.Color(64, 81, 94));
        table6.setText("table6");
        add(table6, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 592, -1, -1));

        table7.setBackground(new java.awt.Color(249, 248, 235));
        table7.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        table7.setForeground(new java.awt.Color(64, 81, 94));
        table7.setText("table7");
        add(table7, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 552, -1, -1));

        table8.setBackground(new java.awt.Color(249, 248, 235));
        table8.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        table8.setForeground(new java.awt.Color(64, 81, 94));
        table8.setText("table8");
        add(table8, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 592, -1, -1));

        umail.setBackground(new java.awt.Color(233, 239, 186));
        umail.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        umail.setForeground(new java.awt.Color(64, 81, 94));
        umail.setText("umail");
        umail.setBorder(null);
        add(umail, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 264, 256, 29));

        upass.setBackground(new java.awt.Color(233, 239, 186));
        upass.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        upass.setForeground(new java.awt.Color(64, 81, 94));
        upass.setText("upass");
        upass.setBorder(null);
        add(upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 388, 250, 29));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/initialHome.png"))); // NOI18N
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 30, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/initialHome.png"))); // NOI18N
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 260, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
        jLabel6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel6MouseMoved

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int i=0;
        try {
                i=st.executeUpdate("update users set Password='"+upass.getText()+"' where name='"+unm+"'");
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verified.png")));
            }   
        catch(Exception e2){System.out.println("Exception aayi h "+e2.getMessage());}                           
        if(i>0)
            JOptionPane.showMessageDialog(null,"Password updated successfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);                                    
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        jLabel7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel7MouseMoved

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try
        {
            otp=rand.nextInt(999999);
            email=umail.getText();
            sendMail(email);
            jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verified.png")));
        }
        catch(Exception e){ System.out.println("sendMail Exception: "+e.getMessage());}
    }//GEN-LAST:event_jLabel7MouseClicked

    public void sendMail(String mail)
    {
        try
        {     
            String host="smtp.gmail.com";
            String user="meet01636@gmail.com";
            String pass="meet0029";
            String to=mail;
            String subject="OTP Request";
            String message="EMAIL VERIFICATION!"
                + "\n\nHi there!"
                + "\nYou have requested to change your email address from "+oldmail+" to "+mail+" on your PHMS account."
                + "\n\nConfirmation OTP code: "+otp
                + "\n\nThanks for trusting on Plant Health Monitoring System."
                + "\nSee you soon on PHMSystem."
                + "\n\nSincerely,"
                + "\nThe PHMS Team";
        
            boolean sessionDebug=false;
            Properties pros=System.getProperties();
            pros.setProperty("mail.trasport.protocol","smtp");
            pros.setProperty("mail.host","smtp.gmail.com");
            pros.put("mail.smtp.port","465");
            pros.put("mail.smtp.auth","true");
            pros.put("mail.debug","true");
            pros.put("mail.smtp.socketFactory.port","465");
            pros.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
            pros.put("mail.smtp.socketFactory.fallback","false");
            
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session mailSession=Session.getDefaultInstance(pros,null);
            mailSession.setDebug(sessionDebug);
            Message msg=new MimeMessage(mailSession);
            msg.setFrom(new InternetAddress(user));
            InternetAddress []address={new InternetAddress(to)};
            msg.setRecipients(Message.RecipientType.TO,address);
            msg.setSubject(subject);
            msg.setText(message);
            Transport transport=mailSession.getTransport("smtp");
            transport.connect(host,user,pass);
            transport.sendMessage(msg,msg.getAllRecipients());
            transport.close();
            JOptionPane.showMessageDialog(null,"OTP is sent to "+mail);
            
            OTP o=new OTP(unm,otp,mail);
            o.setVisible(true);
        }
        catch(Exception e2){
            System.out.println("Exception aayi h sendMail() me"+e2.getMessage());
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unavailable.png")));
            if(e2.getMessage().contains("java.net.UnknownHostException: smtp.gmail.com"))
                JOptionPane.showMessageDialog(null,"Oops !   Network Error","Network Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lpname;
    private javax.swing.JLabel Lpname2;
    private javax.swing.JLabel Lpname5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel table1;
    private javax.swing.JLabel table2;
    private javax.swing.JLabel table3;
    private javax.swing.JLabel table4;
    private javax.swing.JLabel table5;
    private javax.swing.JLabel table6;
    private javax.swing.JLabel table7;
    private javax.swing.JLabel table8;
    private javax.swing.JTextField umail;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField upass;
    // End of variables declaration//GEN-END:variables
}
