package paneles;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import phms.Connect;

public class UserAdd extends javax.swing.JPanel {

    public String dbname=null,unm=null;
    public Statement s;
    public Connect c=new Connect();
    DefaultTableModel model = new DefaultTableModel();

    public UserAdd(String unm) {
        this.unm=unm; 
        dbname=unm.toLowerCase().replaceAll(" ","");        
        s=c.connection(dbname);       
        initComponents();
        
        model.addColumn("Monitored Plants");
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbname+"?useTimezone=true&serverTimezone=IST","root","");                      
            DatabaseMetaData meta=(DatabaseMetaData) con.getMetaData();
            ResultSet rs=meta.getTables(null,null,"%", new String []{"TABLE"});            
            while(rs.next())
            {
                if(rs.getString(1).equals(dbname))
                {
                    String str=rs.getString("TABLE_NAME");
                    model.addRow(new String[]{str});
                }
            }                        
        }
        catch(ClassNotFoundException | SQLException e2){System.out.println("Exception aayi h "+e2.getMessage());}            
        
        ptable.setModel(model);

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) ptable.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);        

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        ptable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );        

        ptable.getTableHeader().setBackground(new Color(209,246,193));
        ptable.getTableHeader().setForeground(new Color(0x40515E));
        ptable.getTableHeader().setFont(new Font("Calbri Light",Font.BOLD,13));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        Lpname2 = new javax.swing.JLabel();
        pnm = new javax.swing.JTextField();
        Lpname3 = new javax.swing.JLabel();
        Combosens1 = new javax.swing.JComboBox<>();
        Combosens2 = new javax.swing.JComboBox<>();
        Lpname4 = new javax.swing.JLabel();
        Combosens3 = new javax.swing.JComboBox<>();
        Lpname5 = new javax.swing.JLabel();
        Btnadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        Btnrmv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 239, 186));

        jLabel5.setBackground(new java.awt.Color(249, 248, 235));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 81, 94));
        jLabel5.setText("Add New Plant");

        Lpname2.setBackground(new java.awt.Color(249, 248, 235));
        Lpname2.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        Lpname2.setForeground(new java.awt.Color(64, 81, 94));
        Lpname2.setText("Plant:");

        pnm.setBackground(new java.awt.Color(233, 239, 186));
        pnm.setFont(new java.awt.Font("Calibri Light", 1, 19)); // NOI18N
        pnm.setForeground(new java.awt.Color(64, 81, 94));
        pnm.setText("Enter Plantname");
        pnm.setBorder(null);
        pnm.setCaretColor(new java.awt.Color(114, 157, 57));
        pnm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnmFocusLost(evt);
            }
        });
        pnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnmActionPerformed(evt);
            }
        });

        Lpname3.setBackground(new java.awt.Color(249, 248, 235));
        Lpname3.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        Lpname3.setForeground(new java.awt.Color(64, 81, 94));
        Lpname3.setText("Sensor 1:");

        Combosens1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Combosens1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Temperature", "Moisture", "Light" }));
        Combosens1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combosens1ActionPerformed(evt);
            }
        });

        Combosens2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Combosens2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Temperature", "Moisture", "Light" }));
        Combosens2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combosens2ActionPerformed(evt);
            }
        });

        Lpname4.setBackground(new java.awt.Color(249, 248, 235));
        Lpname4.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        Lpname4.setForeground(new java.awt.Color(64, 81, 94));
        Lpname4.setText("Sensor 2:");

        Combosens3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Combosens3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Temperature", "Moisture", "Light" }));
        Combosens3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combosens3ActionPerformed(evt);
            }
        });

        Lpname5.setBackground(new java.awt.Color(249, 248, 235));
        Lpname5.setFont(new java.awt.Font("Calibri Light", 1, 17)); // NOI18N
        Lpname5.setForeground(new java.awt.Color(64, 81, 94));
        Lpname5.setText("Sensor 3:");

        Btnadd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Btnadd.setText("Add");
        Btnadd.setOpaque(false);
        Btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnaddActionPerformed(evt);
            }
        });

        ptable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ptable.setGridColor(new java.awt.Color(204, 204, 204));
        ptable.setRowHeight(22);
        ptable.setRowMargin(3);
        ptable.setSelectionBackground(new java.awt.Color(233, 239, 188));
        ptable.setSelectionForeground(new java.awt.Color(54, 98, 43));
        jScrollPane1.setViewportView(ptable);
        if (ptable.getColumnModel().getColumnCount() > 0) {
            ptable.getColumnModel().getColumn(0).setResizable(false);
        }

        Btnrmv.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Btnrmv.setText("Remove");
        Btnrmv.setOpaque(false);
        Btnrmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnrmvActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addai.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lpname2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnm, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Lpname5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Combosens3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Lpname4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Combosens2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Lpname3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Combosens1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(Btnrmv, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel5)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lpname2)
                                    .addComponent(pnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lpname3)
                                    .addComponent(Combosens1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lpname4)
                                    .addComponent(Combosens2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lpname5)
                                    .addComponent(Combosens3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(Btnadd))
                            .addComponent(Btnrmv, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel1))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnmFocusGained
        pnm.setText("");
    }//GEN-LAST:event_pnmFocusGained

    private void pnmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnmFocusLost
        
    }//GEN-LAST:event_pnmFocusLost

    private void pnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnmActionPerformed

    }//GEN-LAST:event_pnmActionPerformed

    private void Combosens1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combosens1ActionPerformed
    }//GEN-LAST:event_Combosens1ActionPerformed

    private void Combosens2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combosens2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combosens2ActionPerformed

    private void Combosens3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combosens3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combosens3ActionPerformed

    private void BtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnaddActionPerformed
        try
        {            
            String urlLink="http://localhost/createtable.php?dbname="+dbname+"&pname="+pnm.getText()+"&s1="+Combosens1.getSelectedItem().toString()+"&s2="+Combosens2.getSelectedItem().toString()+"&s3="+Combosens3.getSelectedItem().toString();
            URL url=new URL(urlLink);
            HttpURLConnection conn=(HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            
            BufferedReader in=new BufferedReader(new InputStreamReader(conn.getInputStream()));
            StringBuffer sb=new StringBuffer();
            String line;
            
            while((line=in.readLine())!=null)
            {
                sb.append(line);
            }
            in.close();
            if(sb.toString().equals("done"))
                JOptionPane.showMessageDialog(null,pnm.getText()+" successfully added for monitoring","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                
       }
        catch(Exception e2){System.out.println("Exception aayi h connect class me "+e2.getMessage());}        
        
    }//GEN-LAST:event_BtnaddActionPerformed

    private void BtnrmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnrmvActionPerformed
        
        int i=ptable.getSelectedRow();
        TableModel tblmdl=ptable.getModel();
        String p=tblmdl.getValueAt(i,0).toString();

        int temp=JOptionPane.showConfirmDialog(null,"Are you sure you want to remove "+p+" from monitoring ?");
        if(temp==0)
        {
            try{
                String urlLink="http://localhost/deletetable.php?db="+dbname+"&tblname="+p;
                URL url=new URL(urlLink);
                HttpURLConnection conn=(HttpURLConnection) url.openConnection();
                conn.setRequestMethod("GET");
            
                BufferedReader in=new BufferedReader(new InputStreamReader(conn.getInputStream()));
                StringBuffer sb=new StringBuffer();
                String line;
            
                while((line=in.readLine())!=null)
                {
                    sb.append(line);
                }
                in.close();
                if(sb.toString().equals("done"))
                    JOptionPane.showMessageDialog(null,p+" removed successfully","Congratulations",JOptionPane.INFORMATION_MESSAGE);
                }
                catch(Exception e2){System.out.println("Exception aayi h connect class me "+e2.getMessage());}        
        }
    }//GEN-LAST:event_BtnrmvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnadd;
    private javax.swing.JButton Btnrmv;
    private javax.swing.JComboBox<String> Combosens1;
    private javax.swing.JComboBox<String> Combosens2;
    private javax.swing.JComboBox<String> Combosens3;
    private javax.swing.JLabel Lpname2;
    private javax.swing.JLabel Lpname3;
    private javax.swing.JLabel Lpname4;
    private javax.swing.JLabel Lpname5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pnm;
    private javax.swing.JTable ptable;
    // End of variables declaration//GEN-END:variables
}
