package phms;   

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import paneles.ComboPanel;

public class Home extends javax.swing.JFrame {

    static String unm="";    
    
    public Home(String unm) {
        this.unm=unm;
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/img/logo.png")).getImage());
        new ComboPanel(bgPanel, new paneles.UserHome(unm,"",""));      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        home = new rsbuttom.RSButtonMetro();
        add = new rsbuttom.RSButtonMetro();
        analysis = new rsbuttom.RSButtonMetro();
        health = new rsbuttom.RSButtonMetro();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bgPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(233, 239, 186));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(233, 239, 186));

        jPanel1.setBackground(new java.awt.Color(198, 227, 119));

        jPanel3.setBackground(new java.awt.Color(198, 227, 119));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 155, 68));
        jLabel2.setText("PLANT");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 155, 68));
        jLabel3.setText("MONITORING");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 155, 68));
        jLabel4.setText("HEALTH");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 155, 68));
        jLabel5.setText("SYSTEM");

        jSeparator1.setBackground(new java.awt.Color(38, 155, 68));
        jSeparator1.setAlignmentX(0.7F);
        jSeparator1.setAlignmentY(0.7F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(38, 155, 68)));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(60, 15));
        jSeparator1.setPreferredSize(new java.awt.Dimension(60, 15));
        jSeparator1.setRequestFocusEnabled(false);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(38, 155, 68));
        jLabel6.setText("v 0.1");
        jLabel6.setToolTipText("");

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_home_page_24px.png"))); // NOI18N
        home.setText("Home");
        home.setBorderPainted(false);
        home.setColorBorde(null);
        home.setColorHover(new java.awt.Color(88, 179, 104));
        home.setColorNormal(new java.awt.Color(88, 179, 104));
        home.setColorPressed(new java.awt.Color(88, 179, 104));
        home.setColorTextHover(new java.awt.Color(91, 91, 91));
        home.setColorTextNormal(new java.awt.Color(91, 91, 91));
        home.setColorTextPressed(new java.awt.Color(91, 91, 91));
        home.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        home.setIconTextGap(20);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_to_clipboard_24px.png"))); // NOI18N
        add.setText(" Add   ");
        add.setColorBorde(null);
        add.setColorHover(new java.awt.Color(204, 228, 144));
        add.setColorNormal(new java.awt.Color(198, 227, 119));
        add.setColorPressed(new java.awt.Color(88, 179, 104));
        add.setColorTextHover(new java.awt.Color(91, 91, 91));
        add.setColorTextNormal(new java.awt.Color(91, 91, 91));
        add.setColorTextPressed(new java.awt.Color(91, 91, 91));
        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.setIconTextGap(16);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        analysis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_statistics_24px.png"))); // NOI18N
        analysis.setText("Analysis");
        analysis.setColorBorde(null);
        analysis.setColorHover(new java.awt.Color(204, 228, 144));
        analysis.setColorNormal(new java.awt.Color(198, 227, 119));
        analysis.setColorPressed(new java.awt.Color(88, 179, 104));
        analysis.setColorTextHover(new java.awt.Color(91, 91, 91));
        analysis.setColorTextNormal(new java.awt.Color(91, 91, 91));
        analysis.setColorTextPressed(new java.awt.Color(91, 91, 91));
        analysis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        analysis.setIconTextGap(20);
        analysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                analysisMousePressed(evt);
            }
        });
        analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysisActionPerformed(evt);
            }
        });

        health.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_heart_health_24px.png"))); // NOI18N
        health.setText("Health ");
        health.setColorBorde(null);
        health.setColorHover(new java.awt.Color(204, 228, 144));
        health.setColorNormal(new java.awt.Color(198, 227, 119));
        health.setColorPressed(new java.awt.Color(88, 179, 104));
        health.setColorTextHover(new java.awt.Color(91, 91, 91));
        health.setColorTextNormal(new java.awt.Color(91, 91, 91));
        health.setColorTextPressed(new java.awt.Color(91, 91, 91));
        health.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        health.setIconTextGap(20);
        health.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                healthMousePressed(evt);
            }
        });
        health.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(38, 155, 68));
        jLabel7.setText("© Copyright 2019 Meet Bhalodia");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogOutBtn.png"))); // NOI18N
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel8MouseMoved(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(analysis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(health, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(health, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(24, 24, 24))
        );

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setLayout(new javax.swing.BoxLayout(bgPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        new ComboPanel(bgPanel, new paneles.UserHome(unm,"",""));
        if(this.home.isSelected()){
            this.home.setColorNormal(new Color(88,179,104));
            this.home.setColorHover(new Color(88,179,104));
            this.home.setColorPressed(new Color(88,179,104));
            
            this.add.setColorNormal(new Color(198,227,119));
            this.add.setColorHover(new Color(204,228,144));
            this.add.setColorPressed(new Color(88,179,104));
            
            this.analysis.setColorNormal(new Color(198,227,119));
            this.analysis.setColorHover(new Color(204,228,144));
            this.analysis.setColorPressed(new Color(88,179,104));
            
            this.health.setColorNormal(new Color(198,227,119));
            this.health.setColorHover(new Color(204,228,144));
            this.health.setColorPressed(new Color(88,179,104));
            
        }else{
            this.home.setColorNormal(new Color(198,227,119));
            this.home.setColorHover(new Color(204,228,144));
            this.home.setColorPressed(new Color(88,179,104));
        }
    }//GEN-LAST:event_homeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        new ComboPanel(bgPanel, new paneles.UserAdd(unm));
        if(this.add.isSelected()){
            this.add.setColorNormal(new Color(88,179,104));
            this.add.setColorHover(new Color(88,179,104));
            this.add.setColorPressed(new Color(88,179,104));
            
            this.home.setColorNormal(new Color(198,227,119));
            this.home.setColorHover(new Color(204,228,144));
            this.home.setColorPressed(new Color(88,179,104));
            
            this.analysis.setColorNormal(new Color(198,227,119));
            this.analysis.setColorHover(new Color(204,228,144));
            this.analysis.setColorPressed(new Color(88,179,104));
            
            this.health.setColorNormal(new Color(198,227,119));
            this.health.setColorHover(new Color(204,228,144));
            this.health.setColorPressed(new Color(88,179,104));
        }else{
            this.add.setColorNormal(new Color(198,227,119));
            this.add.setColorHover(new Color(204,228,144));
            this.add.setColorPressed(new Color(88,179,104));
        }

    }//GEN-LAST:event_addActionPerformed

    private void analysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisActionPerformed
        new ComboPanel(bgPanel, new paneles.UserAnalysis(unm));
        if(this.analysis.isSelected()){
            this.analysis.setColorNormal(new Color(88,179,104));
            this.analysis.setColorHover(new Color(88,179,104));
            this.analysis.setColorPressed(new Color(88,179,104));
            
            this.home.setColorNormal(new Color(198,227,119));
            this.home.setColorHover(new Color(204,228,144));
            this.home.setColorPressed(new Color(88,179,104));
            
            this.add.setColorNormal(new Color(198,227,119));
            this.add.setColorHover(new Color(204,228,144));
            this.add.setColorPressed(new Color(88,179,104));
            
            this.health.setColorNormal(new Color(198,227,119));
            this.health.setColorHover(new Color(204,228,144));
            this.health.setColorPressed(new Color(88,179,104));
        }else{
            this.analysis.setColorNormal(new Color(198,227,119));
            this.analysis.setColorHover(new Color(204,228,144));
            this.analysis.setColorPressed(new Color(88,179,104));
        }
    }//GEN-LAST:event_analysisActionPerformed

    private void healthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthActionPerformed
        new ComboPanel(bgPanel, new paneles.UserHealth(unm));
        if(this.health.isSelected()){
            this.health.setColorNormal(new Color(88,179,104));
            this.health.setColorHover(new Color(88,179,104));
            this.health.setColorPressed(new Color(88,179,104));
            
            this.home.setColorNormal(new Color(198,227,119));
            this.home.setColorHover(new Color(204,228,144));
            this.home.setColorPressed(new Color(88,179,104));
            
            this.analysis.setColorNormal(new Color(198,227,119));
            this.analysis.setColorHover(new Color(204,228,144));
            this.analysis.setColorPressed(new Color(88,179,104));
            
            this.add.setColorNormal(new Color(198,227,119));
            this.add.setColorHover(new Color(204,228,144));
            this.add.setColorPressed(new Color(88,179,104));
        }else{
            this.health.setColorNormal(new Color(198,227,119));
            this.health.setColorHover(new Color(204,228,144));
            this.health.setColorPressed(new Color(88,179,104));
        }
    }//GEN-LAST:event_healthActionPerformed

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        this.home.setSelected(true);
        this.add.setSelected(false);
        this.analysis.setSelected(false);
        this.health.setSelected(false);
    }//GEN-LAST:event_homeMousePressed

    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        this.home.setSelected(false);
        this.add.setSelected(true);
        this.analysis.setSelected(false);
        this.health.setSelected(false);
    }//GEN-LAST:event_addMousePressed

    private void analysisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analysisMousePressed
        this.home.setSelected(false);
        this.add.setSelected(false);
        this.analysis.setSelected(true);
        this.health.setSelected(false);
    }//GEN-LAST:event_analysisMousePressed

    private void healthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthMousePressed
        this.home.setSelected(false);
        this.add.setSelected(false);
        this.analysis.setSelected(false);
        this.health.setSelected(true);
    }//GEN-LAST:event_healthMousePressed

    private void jLabel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseMoved
        jLabel8.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel8MouseMoved

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    int j=JOptionPane.showConfirmDialog(null,"Are you sure you want to Logout?");
    if(j==0)
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(unm).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro add;
    private rsbuttom.RSButtonMetro analysis;
    private javax.swing.JPanel bgPanel;
    private rsbuttom.RSButtonMetro health;
    private rsbuttom.RSButtonMetro home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
